create table apexrest_customers (
    id number generated by default on null as identity primary key,
    name varchar2(200) not null,
    email varchar2(320) not null,
    status varchar2(20) default 'ACTIVE' not null,
    created_at timestamp default systimestamp not null,
    updated_at timestamp default systimestamp not null,
    constraint apexrest_customers_status_ck check (status in ('ACTIVE', 'INACTIVE')),
    constraint apexrest_customers_email_uq unique (email)
);
