-- Optional isolated development fixture. Never run automatically during compilation/import.
-- Apply only to an explicitly authorized project schema; adapt existing data models instead of replacing them.
create table APEXREST_PATTERN_RECORDS (
    ID number generated by default on null as identity primary key,
    NAME varchar2(200 char) not null,
    STATUS varchar2(20 char) default 'Open' not null,
    ROW_VERSION number default 1 not null,
    constraint APEXREST_PATTERN_RECORDS_STATUS check (STATUS in ('Open', 'Closed'))
);
create or replace trigger APEXREST_PATTERN_RECORDS_VERSION
before update on APEXREST_PATTERN_RECORDS
for each row
begin
    :new.ROW_VERSION := :old.ROW_VERSION + 1;
end;
/
